config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resource :question, only: [] do
  	member do
  		get 'next'
  		get 'answer'
  	end
  end
end

app/models/answer.rb
class Answer

	def self.for_question(question)
		question.first_random * question.second_random
	end

end

app/models/question.rb
class Question < ActiveRecord::Base

	validates_presence_of :chapter

	scope :random_chapter, ->(chapter) { where(chapter: chapter).order("RANDOM()") }

	def self.get(chapter)
		random_chapter(chapter).first
	end

	def formatted
		"#{first_random} x #{second_random}"
	end

	def first_random
		rand(question_one_lower..question_one_upper)
	end

	def second_random
		rand(question_two_lower..question_two_upper)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@question = '92 x 98'
		@answer = 9016
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	before_filter :set_chapter_session, only: :next
	before_filter :set_question_session, only: :next

	def next
		render partial: 'question_box', locals: {question: @question.formatted}
	end

	def answer
		session_question = session.fetch(:question, 1)
		question = Question.find(session_question)
		answer = Answer.for_question(question)
		render partial: 'answer_box', locals: {answer: answer}
	end

	private

	def set_chapter_session
		@chapter = params['chapter'] || session[:chapter] || 1
		session[:chapter] = @chapter unless @chapter == session[:chapter]
	end

	def set_question_session
		@question = Question.get(@chapter)
		session[:question] = @question.id
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper

	def chapters
		[
			['Chapter 1', 1],
		  ['Chapter 2', 2],
		  ['Chapter 3', 3],
		  ['Chapter 5', 5]
		]
	end

end

app/views/home/_footer.html.erb
<footer>
  <p class='twitter-logo'>
    <%= link_to(image_tag('twitter-hover.png', alt: 'share with twitter', title: 'Share with Twitter'), 'https://twitter.com/intent/tweet?text=Speed%20Mathematics%20-%20Practise%20exercises%20from%20Speed%20Mathematics%20by%20Bill%20Handley&via=tomkadwill&url=http://speedmathematics.heroku.com', class: 'twitter-image') %>
  </p>
  <p>
    <%= link_to '@tomkadwill', 'https://twitter.com/tomkadwill' %>
  </p>
</footer>

app/views/home/index.html.erb
<h1>Speed Mathematics</h1>

<%= form_tag(next_question_path, method: "get", id: 'chapter-form') do %>

  <p><label class="custom-select">
 	<%= select_tag(:chapter, options_for_select(chapters)) %>
 </label></p>

<% end %>

<div id="content">
	<% if @question %>
		<span id="question"><%= @question %></span>
	<% end %>
</div>

<div id="explanation">
  Select a chapter from <%= link_to 'the book', 'http://www.amazon.co.uk/Speed-Mathematics-Secret-Skills-Calculation/dp/0471467316' %> that you want to practise and click the button to reveal the answer. Click again to generate a new question.
</div>

<%= render 'footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Speed Mathematics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_answer_box.html.erb
<div id="contentAnswer">
	<span id="answer"><%= answer %></span>
</div>

app/views/questions/_question_box.html.erb
<div id="content">
	<span id="question"><%= question %></span>
</div>